name: servi_app_camituresso
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^5.0.0-release-candidate-9.2
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  lottie: ^3.1.2
  flutter_xlider: ^3.5.0
  flutter_rating_bar: ^4.0.1
  get_storage: ^2.1.1

  pretty_dio_logger: ^1.4.0
  flutter_html: ^3.0.0-beta.2
  http_parser: ^4.0.2
  dio: ^5.6.0
  mime: ^1.0.6
  http: ^1.2.2
  connectivity_plus: ^6.0.5
  flutter_widget_from_html: ^0.15.3
  socket_io_client: ^2.0.3+1
  intl: ^0.20.1
  timezone: ^0.10.0
  flutter_timezone: ^4.0.0
  webview_flutter: ^4.4.1
  flutter_custom_tabs: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/dev_images/
    - assets/icons/
    - assets/images/
    - assets/lottie/


  fonts:
    - family: Poppins 
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
