class AssetsIconsPath {
  AssetsIconsPath._();
  static const String google = "assets/icons/google.png";
  static const String account = "assets/icons/account.png";
  static const String call = "assets/icons/call.png";
  static const String chatFill = "assets/icons/chat_fill.png";
  static const String chat = "assets/icons/chat.png";
  static const String home = "assets/icons/home.png";
  static const String location = "assets/icons/location.png";
  static const String logOut = "assets/icons/log_out.png";
  static const String mail = "assets/icons/mail.png";
  static const String notification = "assets/icons/notification.png";
  static const String password = "assets/icons/password.png";
  static const String user = "assets/icons/user.png";
  static const String request = "assets/icons/request.png";
  static const String savaDed = "assets/icons/sava_ded.png";
  static const String notSavaDed = "assets/icons/not_save_ded.png";
  static const String notSavaDed2 = "assets/icons/not_save_ded_2.png";
  static const String search = "assets/icons/search.png";
  static const String searchButton = "assets/icons/search_button.png";
  static const String star = "assets/icons/star.png";
  static const String chatSendButton = "assets/icons/chat_send_button.png";
  static const String camera = "assets/icons/camera.png";
  static const String file = "assets/icons/file.png";
  static const String addImage = "assets/icons/add_image.png";
  static const String paymentMethodCard = "assets/icons/payment_method_card.png";
  static const String about = "assets/icons/about.png";
  static const String privacyPolicy = "assets/icons/privacy_policy.png";
  static const String transactionHistory = "assets/icons/transaction_history.png";
  static const String userHistory = "assets/icons/user_history.png";
  static const String yourPost = "assets/icons/your_post.png";
  static const String actionEdit = "assets/icons/action_edit.png";
  static const String transactionCard = "assets/icons/transaction_card.png";
  static const String backButton = "assets/icons/back_button.png";
  static const String popUpButton = "assets/icons/pop_up_button.png";
}
